# Generated by Django 5.0.7 on 2024-08-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="BeerCategory", new_name="Category",),
    ]
