# Generated by Django 5.0.7 on 2024-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("S", "Beer"), ("SW", "Food"), ("OW", "Soft Drink")],
                max_length=2,
            ),
        ),
    ]
