# Generated by Django 5.0.7 on 2024-08-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_beercategory_category"),
    ]

    operations = [
        migrations.RenameModel(old_name="Beer", new_name="Items",),
        migrations.RenameField(
            model_name="cartitem", old_name="beer", new_name="items",
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="beer", new_name="items",
        ),
    ]
