# Generated by Django 5.0.7 on 2024-12-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_remove_user_groups_remove_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
